image: amazon/aws-cli:2.15.59

pipelines:
  branches:
    master:
      - step:
          name: Deploy from Main Branch
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - export TAG_NAME=$SP_BC_RTSQ_PRO_SERVER_TAG_NAME
            - export COMMAND="sudo -u ec2-user ${RTSQ_PRO_COMMAND}/bigcommerce/bc-fe/remote-script.sh"
            - chmod +x ./bb-scripts/run-ssm-command.sh
            - ./bb-scripts/run-ssm-command.sh

            
    dev:
      - step:
          name: Deploy from Dev Branch
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - export TAG_NAME="$DEV_SERVER_TAG_NAME"
            - export COMMAND='["sudo -u apx-bc-01 bash -c \"cd '"${DEV_COMMAND}"'/bigcommerce/bc-fe && git stash && git fetch && git checkout && git pull && export NODE_OPTIONS=--openssl-legacy-provider && npm run build && ./remote-script.sh\""]'   
            - chmod +x ./bb-scripts/run-ssm-command.sh
            - ./bb-scripts/run-ssm-command.sh 

            
    free_shipping_in_override_rule:
      - step:
          name: Deploy from Staging Branch
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - export TAG_NAME=$STAGING_SERVER_TAG_NAME
            - export COMMAND='["sudo -u apx-bc-01 bash -c \"cd '"${STAGING_COMMAND}"'/bigcommerce/bc-fe && git stash && git fetch && git checkout free_shipping_in_override_rule && git pull && export NODE_OPTIONS=--openssl-legacy-provider && npm run build &&  ./remote-script.sh\""]'
            - chmod +x ./bb-scripts/run-ssm-command.sh
            - ./bb-scripts/run-ssm-command.sh 
