# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.29
options:
  max-time: 60
pipelines:
  branches:
    development-branch:
    - step:
        caches:
          - composer
        script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'apx-bc-01'
              SERVER: '44.207.204.55'
              MODE: 'command'
              COMMAND: '/var/www/html/bigcommerce/bc-fe/remote-script.sh'
              
    require-nmfc-checkbox-wwe-group-carriers:
    - step:
          caches:
            - composer
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $BC_STAGING_SSH_USER
                SERVER: $STAGING_SERVER_IP
                MODE: 'command'
                COMMAND: 'cd $STAGING_COMMAND/bigcommerce/bc-fe && git stash && git pull && export NODE_OPTIONS=--openssl-legacy-provider && npm run build && ./remote-script.sh'
              
    master:
      - step:
          caches:
            - composer
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'ec2-user'
                SERVER: '34.197.112.152'
                MODE: 'command'
                COMMAND: '/var/www/html/bigcommerce/bc-fe/remote-script.sh'
