# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.29
options:
  max-time: 60
pipelines:
  branches:
    feature/add-carrier-unishipper-ltl:
    - step:
        caches:
          - composer
        script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'apx-bc-01'
              SERVER: '44.207.204.55'
              MODE: 'command'
              COMMAND: '/home/apx-bc-01/html/bc-fe/remote-script.sh'
              
    feature/large-cart-settings:
    - step:
          caches:
            - composer
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'apx-bc-01'
                SERVER: '52.87.17.243'
                MODE: 'command'
                COMMAND: '/var/www/html/bigcommerce/bc-fe/remote-script.sh'
              
    master:
    - step:
        caches:
          - composer
        script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'ec2-user'
              SERVER: '34.197.112.152'
              MODE: 'command'
              COMMAND: '/var/www/html/bigcommerce/bc-fe/remote-script.sh'
              
    ws-elb:
    - step:
        caches:
          - composer
        script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'ec2-user'
              SERVER: '54.159.170.144'
              MODE: 'command'
              COMMAND: '/var/www/html/ws/carriers/cerasis/remote-script.sh'
